[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "counter>=1.0.0",
    "django-task-manager>=0.1",
    "simplecalculator>=0.0.4",
]
